#!/bin/bash

DEPLOYMENT_PATH = '/home/ec2-user/sociami_staging/'
APP_NAME = 'sociami_stg'

if [ "$DEPLOYMENT_GROUP_NAME" == "Production" ]; then
  DEPLOYMENT_PATH = '/home/ec2-user/sociami_production/'
  APP_NAME = 'sociami_prd'
fi

cd $DEPLOYMENT_PATH
pm2 describe $APP_NAME > /dev/null
RUNNING=$?

if [ "${RUNNING}" -ne 0 ]; then
  pm2 stop server.js --name $APP_NAME
else
  pm2 stop $APP_NAME
fi
